vpc_cidr_block      = "192.168.0.0/24"
subnet_cidr_block   = "192.168.0.0/26"
env_prefix          = "dev"
avail_zone          = "ap-south-1a"
ami_type            = "t2.micro"
public_key_location = "/home/nasir.rayeen/.ssh/id_rsa.pub"